name: publisher

on:
  workflow_dispatch:
  # schedule:
  #   # Runs every 1 hour
  #   - cron: '0 */1 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
  
    - name: Before Publish
      run: |
        pwd
        ls -la
        cat .github/workflows/publisher.json

    - name: Publish 🔧 
      run: |
        node .github/workflows/publisher.js
      # env:
      #     TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      #     TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      #     TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      #     INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

    - name: After Publish
      run: |
        pwd
        ls -la
        cat .github/workflows/publisher.json
