name: publisher

on:
  workflow_dispatch:
  schedule:
    # Runs everyday at 1:00 PM UTC (6:00 AM PDT)
    - cron: "0 13 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Publish 🔧
        run: |
          cat publisher.json
          npm install
          npm run publish
          cat publisher.json
          git config --global user.name 'Valentin Podkamennyi'
          git config --global user.email 'vpodk@users.noreply.github.com'
          git add -A
          git commit -m "[skip ci] Updated publisher JSON data."
          git push
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        #     INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
