name: publisher

on:
  workflow_dispatch:
  # schedule:
  #   # Runs every 1 hour
  #   - cron: '0 */1 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Publish 🔧 
      run: |
        cat publisher.json
        node .github/workflows/publisher.js "$PWD/publisher.json"
        cat publisher.json
        git config --global user.name 'Valentin Podkamennyi'
        git config --global user.email 'vpodk@users.noreply.github.com'
        git add -A
        git commit -m "[skip ci] Updated publisher JSON data."
        git push
      # env:
      #     TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      #     TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      #     TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      #     INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
