name: publisher

on:
  workflow_dispatch:
  # schedule:
  #   # Runs every 1 hour
  #   - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: publisher
  
    - name: Display structure of downloaded files
      run: |
        pwd
        ls -R

    # - name: Install and Publish 🔧 
    #   run: |
    #     node publisher.js
    #   # env:
    #   #     TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
    #   #     TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
    #   #     TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
    #   #     TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    #   #     INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: publisher
        path: publisher.json
